uploads = []
generated = []

[[outputs]]
id = "zFHxcCacC3D4tb2SYQnAj"
uri = "file://artifacts/faucet-hub/public/logo.svg"
type = "image"
title = "ChainDrop Logo v2 (SVG)"

[[outputs]]
id = "eyo0UP3EKjY3UuNAiXf1X"
uri = "file://ChainDrop.zip"
type = "unspecified"
title = "ChainDrop - Full Source Code"
